_commit: fe6ed23
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
docs_slug: niche
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: niche
project_description: A vendorable toolset for library and framework developers
publish_on_pypi: true
pypi_project_description: A vendorable toolset for library and framework developers
pypi_project_name: niche
python_version: '3.8'
repo_name: niche
tests: true
use_precommit: true
visibility: public
